### ISSUE TITLE
Implement chat completion streaming

### ISSUE THREAD

**Issue by sashabaranov** [sashabaranov/go-gpt3#100]
Similar to `CreateCompletion` and `CreateCompletionStream`, we need a `CreateChatCompletionStream` for `CreateChatCompletion`.

**Comment by NICEXAI** [comment]
I'm glad I've implemented this feature before now. #101

**Comment by sashabaranov** [comment]
Implemented in https://github.com/sashabaranov/go-gpt3/pull/101
