### ISSUE TITLE
How to use conversation context for complete API ?

### ISSUE THREAD

**Issue by Vaayne** [sashabaranov/go-gpt3#38]
It seems each API request returns a new conversation, it can't answer based on the previous conversation.
So how can I use this API, and keep the conversation context?

**Comment by sashabaranov** [comment]
@Vaayne, sorry, I don't quite understand what you mean here. The completion [API doc](https://beta.openai.com/docs/api-reference/completions/create) says:

> Given a prompt, the model will return one or more predicted completions, and can also return the probabilities of alternative tokens at each position.

So there is no concept of "conversation" here, it's not ChatGPT.

**Comment by Vaayne** [comment]
@sashabaranov Thanks for your reply. It's my misunderstanding, sorry for the confusion.
