### ISSUE TITLE
Set timeout based on context sent and not default 1minute

### ISSUE THREAD

**Issue by vshelvankar** [sashabaranov/go-gpt3#50]
I would like to have timeout configurable or better pick from the context sent.
Currently this library has it as default 1minute but most of complex the API calls to openai goes beyond 1min

**Comment by sashabaranov** [comment]
@vshelvankar did you try `context.WithTimeout`? https://golang.cafe/blog/golang-context-with-timeout-example.html

**Comment by vshelvankar** [comment]
Yes. It did not help

I suspect this config in gogpt3 package is setting all timeout to 1 min. timeout in ctx is not overridden may be ?
func newTransport() *http.Client {
	return &http.Client{
		Timeout: time.Minute,
	}
}

**Comment by sashabaranov** [comment]
@vshelvankar fixed, thanks!
