### ISSUE TITLE
API support for beta version 

### ISSUE THREAD

**Issue by vimitdhawan** [sashabaranov/go-gpt3#55]
Hi Team,

I have tried to use the codex model, but there is no support for the beta version API. Do you guys think we should add support for the beta version API? I would be happy to help with this.

**Comment by sashabaranov** [comment]
Hey @vimitdhawan, which model do you have in mind? I've just tested `code-davinci-002`, and it works well. See example below:

```go

package main

import (
	"context"
	"fmt"
	gogpt "github.com/sashabaranov/go-gpt3"
)

func main() {
	c := gogpt.NewClient("your token")
	ctx := context.Background()

	req := gogpt.CompletionRequest{
		Model:     gogpt.CodexCodeDavinci002, // or just "code-davinci-002"
		MaxTokens: 300,
		Prompt:    "Simple game written in C:\n\n#include <stdio.h>",
	}
	resp, err := c.CreateCompletion(ctx, req)
	if err != nil {
		return
	}
	fmt.Println(resp.Choices[0].Text)
}
```

**Comment by vimitdhawan** [comment]
@sashabaranov Codex. It's in a beta state. I think we can add support for them.
<img width="784" alt="Screenshot 2023-01-26 at 4 33 36 PM" src="https://user-images.githubusercontent.com/19369610/214802938-9d5603e7-ac05-4b46-b441-09a6106df71e.png">

**Comment by sashabaranov** [comment]
@vimitdhawan we already support them, the example above uses the Codex model, it's API ids are `code-davinci-002` and `code-cushman-001`

**Comment by vimitdhawan** [comment]
@Sashbaranov I have tried to use it before but I did not see maybe I missed it. Let me close this one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vimitdhawan** [comment]
It's already implemented.
