### ISSUE TITLE
support custom  stream `emptyMessagesLimit`

### ISSUE THREAD

**Issue by Licoy** [sashabaranov/go-gpt3#70]

**Comment by thanksloving** [comment]
yes,it always get 'stream has sent too many empty messages'

**Comment by sashabaranov** [comment]
@Licoy @thanksloving this is supported now. Please do `go get -u github.com/sashabaranov/go-gpt3` and after that, you can configure the limit like that:

```go
config := gogpt.DefaultConfig("auth token")
config.EmptyMessagesLimit = 10000

client := gogpt.NewClientWithConfig(config)
```

**Comment by Licoy** [comment]
@sashabaranov thanks
