### ISSUE TITLE
Is there a plan to add a retry to the request

### ISSUE THREAD

**Issue by eryajf** [sashabaranov/go-gpt3#76]
For some practical reasons, requests in my place occasionally time out, so do you plan to add the ability to retry in the project?

**Comment by sashabaranov** [comment]
@eryajf Hey, retrying is definitely out of the scope of this library. You can increase timeout using [context.WithTimeout](https://golang.cafe/blog/golang-context-with-timeout-example.html) or implement retrying yourself, there are some libraries to do that out there, e.g., https://github.com/avast/retry-go
