### ISSUE TITLE
add http status checking in CreateCompletionStream

### ISSUE THREAD

**Issue by shenweijiekdel** [sashabaranov/go-gpt3#81]
CreateCompletionStream: 

http response status not 2xx but return empty stream insteat of  reporting error

expected: return an error

**Comment by sashabaranov** [comment]
Updated the stream logic in #86, could you please re-try after doing `go get -u github.com/sashabaranov/go-gpt3` ?

**Comment by shenweijiekdel** [comment]
thanks
