### ISSUE TITLE
the stream always return EOF

### ISSUE THREAD

**Issue by imsprojo2fan** [sashabaranov/go-gpt3#82]
func test1(key, input string, callback func(message string)) {

	config := gogpt.DefaultConfig(key)
	config.EmptyMessagesLimit = 10000
	c := gogpt.NewClientWithConfig(config)
	ctx := context.Background()

	req := gogpt.CompletionRequest{
		Model:     gogpt.GPT3TextDavinci003,
		MaxTokens: 5,
		Prompt:    input,
		Stream:    true,
	}

	stream, err := c.CreateCompletionStream(ctx, req)

	if err != nil {
		return
	}
	defer stream.Close()
	i := 0
	for {
		i++
		response, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			fmt.Println(err.Error())
			fmt.Println("Stream finished")
			return
		}
		if err != nil {
			fmt.Printf("Stream error: %v\n", err)
			return
		}
		var txt string
		if len(response.Choices) > 0 {
			txt = response.Choices[0].Text
		}
		callback(txt)
		//fmt.Printf("Stream response: %v\n", response.Choices[0])
	}
}

the version is v1.2.0
thanks

**Comment by sashabaranov** [comment]
@imsprojo2fan could you also provide your `input` please?

**Comment by imsprojo2fan** [comment]
> @imsprojo2fan could you also provide your `input` please?

just "hello"
It seems that the official service stopped?Can you still use it?

**Comment by sashabaranov** [comment]
Yeah, OpenAI has an outage https://status.openai.com/incidents/mq5jgswy45fr
