### ISSUE TITLE
Support new chat API (POST /chat/completions)

### ISSUE THREAD

**Issue by esgoode** [sashabaranov/go-gpt3#89]
OpenAI announced support for a [new chat API](https://platform.openai.com/docs/api-reference/chat) like chatGPT. This has a similar request and response model to the completions endpoint but with slight variations.

POST: https://api.openai.com/v1/chat/completions

Request:
```json
{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "Hello!"}]
}

```

Response:
```json
{
  "id": "chatcmpl-123",
  "object": "chat.completion",
  "created": 1677652288,
  "choices": [{
    "index": 0,
    "message": {
      "role": "assistant",
      "content": "\n\nHello there, how may I assist you today?",
    },
    "finish_reason": "stop"
  }],
  "usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
}
```

Further details can be found here: https://platform.openai.com/docs/guides/chat

**Comment by itsahedge** [comment]
Eagerly waiting for this support for the new models.

**Comment by sashabaranov** [comment]
Added support for ChatGPT API. Would love your feedback, folks! 🙌🏻

**Comment by sashabaranov** [comment]
Please do `go get -u github.com/sashabaranov/go-gpt3` to update

**Comment by wzhanjun** [comment]
Some parameters are missing. like "stream"

**Comment by Jrpl1228** [comment]
Hola como funciona esto
