### ISSUE TITLE
GPT3Dot5Turbo0301 model always return EOF

### ISSUE THREAD

**Issue by imsprojo2fan** [sashabaranov/go-gpt3#93]
I have upgraded to the latest version but it always return EOF, and the previous version was normal

```
func test1(key, input string, callback func(message string)) {
	config := gogpt.DefaultConfig(key)
	config.EmptyMessagesLimit = 10000
	c := gogpt.NewClientWithConfig(config)
	ctx := context.Background()

	req := gogpt.CompletionRequest{
		Model:     gogpt.GPT3Dot5Turbo0301,
		MaxTokens: 100,
		Prompt:    input,
		Stream:    true,
	}
	stream, err := c.CreateCompletionStream(ctx, req)
	if err != nil {
		return
	}
	defer stream.Close()
	i := 0
	for {
		i++
		response, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			fmt.Println(err.Error())
			fmt.Println("Stream finished")
			return
		}

		if err != nil {
			fmt.Printf("Stream error: %v\n", err)
			return
		}
		var txt string
		if len(response.Choices) > 0 {
			txt = response.Choices[0].Text
		}
		callback(txt)
		//fmt.Printf("Stream response: %v\n", response.Choices[0])
	}
}
key := "sk-Z5vCOAEQ3IINgZ0KpzDkT3BlbkFJ******7BQtM"
test1(key, "hello", func(message string) {
		fmt.Print(message)
	})
```

**Comment by eryajf** [comment]
@imsprojo2fan 你的代码内种暴漏了key哦，可以重置掉

**Comment by imsprojo2fan** [comment]
> @imsprojo2fan 你的代码内种暴漏了key哦，可以重置掉

我限制了使用，如果他测试完就会把这个key删了

**Comment by wzhanjun** [comment]
用错方法了应该是 CreateChatCompletion，

**Comment by jmt99** [comment]
您是更换了 key么？为什么我使用 text_v3的模型key,用不了GPT3Dot5Turbo0301

**Comment by imsprojo2fan** [comment]
> 您是更换了 key么？为什么我使用 text_v3的模型key,用不了GPT3Dot5Turbo0301

上面那个是新创建的key，也是一直返回EOF，调用3.0模型倒是可以正常

**Comment by jmt99** [comment]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/45818615/222316998-7f322968-0945-4679-b79b-9b8391b99025.png">   把这个 error 打印出来

**Comment by imsprojo2fan** [comment]
> <img alt="image" width="447" src="https://user-images.githubusercontent.com/45818615/222316998-7f322968-0945-4679-b79b-9b8391b99025.png"> 把这个 error 打印出来

这里正常，它是读的时候返回EOF
response, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			fmt.Println(err.Error())
			fmt.Println("Stream finished")
			return err
		}

**Comment by smile-magic** [comment]
> > <img alt="image" width="447" src="https://user-images.githubusercontent.com/45818615/222316998-7f322968-0945-4679-b79b-9b8391b99025.png"> 把这个 error 打印出来
> 
> 这里正常，它是接收的时候返回EOF response, err := stream.Recv() if errors.Is(err, io.EOF) { fmt.Println(err.Error()) fmt.Println("Stream finished") return err }

你好,你的问题解决了吗?

**Comment by imsprojo2fan** [comment]
> > > <img alt="image" width="447" src="https://user-images.githubusercontent.com/45818615/222316998-7f322968-0945-4679-b79b-9b8391b99025.png"> 把这个 error 打印出来
> > 
> > 
> > 这里正常，它是接收的时候返回EOF response, err := stream.Recv() if errors.Is(err, io.EOF) { fmt.Println(err.Error()) fmt.Println("Stream finished") return err }
> 
> 你好,你的问题解决了吗?


`func AITwo(input, wsKey string) (gogpt.ChatCompletionResponse, error) {

	InitAiClient()

	var MessageArr []gogpt.ChatCompletionMessage
	var ccm gogpt.ChatCompletionMessage
	ccm.Role = "system"
	ccm.Content = "You are a helpful assistant."
	MessageArr = append(MessageArr, ccm)

	ccm.Role = "user"
	ccm.Content = input
	MessageArr = append(MessageArr, ccm)

	cacheVal, _ := LastRespMap.Load(wsKey)
	ccm.Role = "assistant"
	ccm.Content = other.ParseString(cacheVal)
	MessageArr = append(MessageArr, ccm)

	req := gogpt.ChatCompletionRequest{
		Model:    gogpt.GPT3Dot5Turbo0301,
		Messages: MessageArr,
	}
	resp, err := Client.CreateChatCompletion(Ctx, req)
	return resp, err
}`
