### ISSUE TITLE
The request interface and parameters of the model gpt-3.5 have changed

### ISSUE THREAD

**Issue by eryajf** [sashabaranov/go-gpt3#95]
new interface address：https://platform.openai.com/docs/api-reference/chat/create

Updated the request interface, as well as the request parameters, there may be a lot of things that need to be changed

I'd like to know if I'm already following up.

**Comment by eryajf** [comment]
thank you, i see https://github.com/sashabaranov/go-gpt3/pull/90

**Comment by obiscr** [comment]
It looks like there is no way to get the token consumed each time in the case of using stream.
