### ISSUE TITLE
gpt3dot5trurbo error

### ISSUE THREAD

**Issue by jmt99** [sashabaranov/go-gpt3#98]
when i change model to gpt3dot5truo api return error msg like this :

error, status code: 404, message: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?

**Comment by LightningDev** [comment]
You need to change to ChatCompletion. Here is an example:

```
// Generate the answer using GPT 3.5
req := gogpt.ChatCompletionRequest{
	Model:    gogpt.GPT3Dot5Turbo0301,
	Messages: []gogpt.ChatCompletionMessage{gptMessage},
}

resp, err := client.CreateChatCompletion(ctx, req)
```
Hope this help!

**Comment by jmt99** [comment]
> You need to change to ChatCompletion. Here is an example:
> 
> ```
> // Generate the answer using GPT 3.5
> req := gogpt.ChatCompletionRequest{
> 	Model:    gogpt.GPT3Dot5Turbo0301,
> 	Messages: []gogpt.ChatCompletionMessage{gptMessage},
> }
> 
> resp, err := client.CreateChatCompletion(ctx, req)
> ```
> 
> Hope this help!

thank you 

best wish
