### ISSUE TITLE
Streaming response example model using gpt-3.5-turbo

### ISSUE THREAD

**Issue by smile-magic** [sashabaranov/go-gpt3#99]
Streaming Response Example Model Using gpt-3.5-turbo, stream.Recv always returns isFinished , text-davinci-003 is fine

**Comment by sashabaranov** [comment]
@sashabaranov seems like `gpt-3.5-turbo` is only available for chat completion, i.e., `CreateChatCompletion`. It does not support streaming yet

**Comment by sashabaranov** [comment]
@smile-magic streaming is now supported, see #101 and v1.3.2 release
